### PR TITLE
Added typehints following doctype that return types are all floats  T…

### PR DESCRIPTION
**Pull request by BrandonGoding**
#32 Added type hints following doctypes that return values are floats. Ran testss and they all passed

### CODE REVIEW

**Comment by dpalmasan** [comment]
Looks good! Could you add the following for the constructor?

In imports:

```python
from spacy.tokens import Doc
from typing import Dict
from typing import Optional
```

Then in the constructor:

```python
def __init__(self, doc: Doc, lemmatizer: Optional[Dict[str, str]]=None):
```

Thanks!

**Comment by dpalmasan** [comment]
You might need to install the pre-commits to avoid the lint errors, which will automatically fix the lint issues on commit.

**Comment by BrandonGoding** [comment]
> You might need to install the pre-commits to avoid the lint errors, which will automatically fix the lint issues on commit, or just use the output from the Lint stage to fix the lint fail.

Thanks, that was the key!   This was a fun little project to learn how pull requests work.  Thanks for the oppertunity

**Comment by dpalmasan** [comment]
Sure! Merging, thanks for the commit!

**Pull request merged**
